# -*- coding: utf-8 -*-
import json
import os

i18n_dir = r"C:\dev\scheme-mate-ai\mobile\flutter_app\assets\i18n"

en_path = os.path.join(i18n_dir, "en.json")
with open(en_path, "r", encoding="utf-8") as f:
    en_dict = json.load(f)

# Master translation mappings for remaining 10 official languages
remaining_translations = {
    "doi": {
        "select_your_language": "अपनी मनपसंद भाषा चुनौ",
        "select_language_subtitle": "सारे ऐप च इस्तेमाल करने आस्तै अपनी भाषा चुनौ:",
        "welcome_header": "SchemeMate AI च स्वागत ऐ",
        "welcome_subheading": "अपने व्यापार आस्तै सरकारी योजनाएं ते कर्जा अपनी भाषा च लब्भो।",
        "feature_ai_matching": "व्यक्तिगत योजना चयन",
        "feature_ai_matching_desc": "व्यापार, उम्र ते जाति दे हिसाबै कन्नै योजना लब्भो।",
        "feature_docs": "जरूरी दस्तावेज़ें दी सूची",
        "feature_docs_desc": "आवेदन करने थमां पैह्ले जरूरी प्रमाणपत्रें दी सूची।",
        "feature_portal": "सरकारी पोर्टल दा सीधा लिंक",
        "feature_portal_desc": "सरकारी वेबसाइट पर इक क्लिक च सुरक्षित पहुंच।",
        "btn_create_account": "नवां खाता बनाओ / पंजीकरण",
        "btn_login": "अपने खाते च लॉगिन करो",
        "btn_continue": "पंजीकरण जारी रखो",
        "btn_demo_login": "डेमो लॉगिन (ramesh@example.com)",
        "login_title": "SchemeMate AI लॉगिन",
        "create_account_title": "नवां खाता बनाओ",
        "tab_login": "लॉगिन",
        "tab_create_account": "खाता बनाओ",
        "registered_email": "रजिस्टर्ड ईमेल पता",
        "email_hint": "जियां: name@example.com",
        "password": "पासवर्ड",
        "password_hint": "अपना पासवर्ड पाओ",
        "password_min_hint": "घट्टो-घट्ट ६ अक्षर",
        "full_name": "पूरा नांय",
        "full_name_hint": "जियां: रमेश कुमार",
        "phone_number": "फोन नंबर",
        "phone_hint": "১০-अंकी मोबाइल नंबर",
        "btn_login_submit": "लॉगिन करो",
        "btn_register_submit": "खाता बनाओ ते OTP हासिल करो",
        "otp_title": "ईमेल OTP दी जांच करो",
        "otp_subtitle": "ईमेल पर भेजा गेदा ६-अंकी कोड पाओ:",
        "resend_otp": "परतियै OTP भेजो",
        "resend_in": "{seconds} सेकेंडें च भेजो",
        "verify_otp_btn": "OTP जांचो ते खाता चालू करो",
        "cancel": "रद्द करो",
        "hello_user": "नमस्ते, {name} 👋",
        "edit_form": "फॉर्म बदलो",
        "details_prefix": "📝 विवरण: ",
        "age_chip": "उम्र: {age} बर्ष",
        "category_chip": "वर्ग: {category}",
        "income_chip": "आम्दनी: ₹{income}/बर्ष ({source})",
        "verified_chip": "प्रमाणित: {type} (#{number})",
        "verified_chip_no_num": "प्रमाणित: {type}",
        "profile_completion": "प्रोफाइल पूरा: ",
        "suggested_schemes": "तुंदे आस्तै सुझाई गेदियां योजनाएं",
        "refresh_suggestions": "रिफ्रेश करो",
        "no_suggestions": "कोई योजना नेईं ऐ। प्रोफाइल पूरा करो।",
        "view_required_details_btn": "जरूरी विवरण देखो ते आवेदन करो",
        "offline_mode_active": "ऑफलाइन मोड चालू ऐ",
        "change_language": "भाषा बदलो",
        "required_details_title": "जरूरी विवरण",
        "why_matches_heading": "एह् योजना तुंदे आस्तै की सही ऐ",
        "required_certificates_heading": "जरूरी प्रमाणपत्र ते कागजात",
        "prepare_before_applying": "आवेदन थमां पैह्ले एह् तैयार रखो:",
        "badge_required": "जरूरी",
        "badge_optional": "ऐच्छिक",
        "standard_kyc_note": "साधारण KYC दस्तावेज़ जरूरी:\n• आधार कार्ड\n• पैन कार्ड\n• बैंक पासबुक\n• फोटो",
        "apply_online_btn": "ऑनलाइन आवेदन करो",
        "redirect_notice": "तुसेंगी सरकारी वेबसाइट पर लेया जागा",
        "no_portal_url": "कोई सरकारी लिंक नेईं ऐ।",
        "action_plan_title": "आवेदन कार्य योजना",
        "action_plan_for": "{scheme} आस्तै योजना",
        "administered_by": "प्रशासन: {ministry}",
        "step_1_title": "पात्रता जांचो",
        "step_1_desc": "उम्र ते आम्दनी नियमें कन्नै मिलाओ।",
        "step_2_title": "दस्तावेज़ सूची बनाओ",
        "step_2_desc": "आधार ते पैन कार्ड जमा करो।",
        "step_3_title": "पूरा करो",
        "step_3_desc": "OCR कन्नै जांच करो।",
        "step_4_title": "वेबसाइट खोह्लो",
        "step_4_desc": "सरकारी पोर्टल पर जाओ।",
        "step_5_title": "जमा करो ते ट्रैक करो",
        "step_5_desc": "नंबर संभालियै रखो।",
        "open_verified_portal_btn": "सरकारी पोर्टल खोह्लो",
        "profile_form_title": "व्यापारिक प्रोफाइल",
        "profile_banner_info": "व्यापार दा विवरण पाओ। AI योजना लब्घग।",
        "field_company_name": "१. कंपनी दा नांय",
        "hint_company_name": "जियां: श्री लक्ष्मी टेक्सटाइल",
        "field_business_desc": "२. व्यापार दा विवरण",
        "hint_business_desc": "जियां: कपड़े बनाना ते बेचना",
        "field_business_type": "३. व्यापार दी किस्म",
        "field_state": "४. राज्य",
        "field_age": "५. व्यापारी दी उम्र",
        "hint_age": "उम्र",
        "field_annual_income": "६. सालाना आम्दनी (₹)",
        "hint_annual_income": "सालाना आम्दनी",
        "field_income_source": "७. आम्दनी दा ज़रिया",
        "field_category_caste": "८. सामाजिक वर्ग / जाति",
        "field_certificate_section": "९. प्रमाणपत्र नंबर (जरूरी)",
        "certificate_section_desc": "सबसिडी आस्तै प्रमाणपत्र नंबर पाओ।",
        "select_cert_type": "प्रमाणपत्र चुनौ",
        "cert_linked": "जुड़े दा प्रमाणपत्र: ",
        "btn_save_profile": "प्रोफाइल संभालो ते योजनाएं देखो ->",
        "field_custom_business_type": "व्यापार दी किस्म लिक्खो",
        "hint_custom_business_type": "जियां: ड्रोन सेवा",
        "field_custom_state": "राज्य / केंद्र शासित प्रदेश",
        "hint_custom_state": "जियां: जम्मू ते कश्मीर",
        "field_custom_caste": "जाति दा नांय पाओ",
        "hint_custom_caste": "जियां: डोगरा, राजपूत आदि",
        "view_all_languages": "सब्बै २३ भाषाएं देखो ->",
        "last_date": "आखरी तारीख",
        "calc_title": "योजना कर्जा ते EMI कैलकुलेटर",
        "calc_presets_heading": "मशहूर योजनाएं:",
        "calc_loan_amount_label": "जरूरी कर्जा:",
        "calc_interest_rate_label": "ब्याज दर (%):",
        "calc_moratorium_label": "छूट दा समय (महीने):",
        "calc_tenure_label": "कुल वापस मोड़ने दा समय:",
        "calc_subsidy_pct_label": "सरकारी सबसिडी (%):",
        "calc_monthly_emi": "महीने दी EMI",
        "calc_moratorium_monthly": "छूट दे समय दी EMI",
        "calc_subsidy_credit": "सबसिडी दी रकम",
        "calc_gross_loan": "कुल कर्जा:",
        "calc_net_loan": "बाकी कर्जा:",
        "calc_total_interest": "कुल ब्याज:",
        "calc_total_outflow": "कुल देने हाली रकम:",
        "months_suffix": "महीने",
        "months_grace": "महीने छूट",
        "partner_locator_title": "नेड़े दे बैंक ते साझेदार",
        "live_gps": "लाइव GPS",
        "gps_update": "GPS ताजा करो",
        "partners_found": "साझेदार लब्भे",
        "eligible_healthy": "सही ते सक्रिय",
        "get_directions": "नक्शे पर रस्ता देखो",
        "routing_disabled": "रस्ता बंद (ज्यादा NPA)",
        "calculate_emi": "EMI निकालो",
        "locate_partner": "साझेदार लब्भो"
    },
    "kok": {
        "select_your_language": "तुमची आवडती भास वोंचात",
        "select_language_subtitle": "सगळ्या ॲपांत वापरपा खातीर तुमची सोपेपणाची भास वोंचात:",
        "welcome_header": "SchemeMate AI त तुमचे येवकार आसा",
        "welcome_subheading": "तुमच्या व्यवसाया खातीर सरकारी येवजण्यो, अनुदानां आनी रीण सुविधेची माहिती तुमच्या भाशेंत मेळयात.",
        "feature_ai_matching": "खाजगी येवजण जुळवणी",
        "feature_ai_matching_desc": "व्यवसाय, पिराय आनी जाती प्रमाणे योग्य येवजण वोंचता.",
        "feature_docs": "गरजेच्या कादगपत्रांची वळेरी",
        "feature_docs_desc": "अर्ज करपा आदी गरजेच्या दाखल्यांची स्पष्ट वळेरी.",
        "feature_portal": "सरकारी पोर्टलाची थेट लिंक",
        "feature_portal_desc": "सरकारी अर्जाच्या वेबसाईटार एका क्लिकाने सुखरूप प्रवेश.",
        "btn_create_account": "नवें खातें तयार करात / नोंदणी करात",
        "btn_login": "तुमच्या खात्यांत लॉगिन करात",
        "btn_continue": "नोंदणी फुडें व्हारात",
        "btn_demo_login": "डेमो लॉगिन (ramesh@example.com)",
        "login_title": "SchemeMate AI लॉगिन",
        "create_account_title": "नवें खातें तयार करात",
        "tab_login": "लॉगिन",
        "tab_create_account": "खातें तयार करात",
        "registered_email": "नोंदणी केल्लो ईमेल पत्तो",
        "email_hint": "देखून: name@example.com",
        "password": "पासवर्ड",
        "password_hint": "तुमचो पासवर्ड घालात",
        "password_min_hint": "उण्यांत उणे ६ अक्षरां",
        "full_name": "पुराय नांव",
        "full_name_hint": "देखून: रमेश कुमार",
        "phone_number": "फोन नंबर",
        "phone_hint": "१० अंकी मोबाईल नंबर",
        "btn_login_submit": "लॉगिन करात",
        "btn_register_submit": "खातें तयार करात आनी OTP मेळयात",
        "otp_title": "ईमेल OTP तपासात",
        "otp_subtitle": "ईमेलाचेर धाडिल्लो ६ अंकी कोड घालात:",
        "resend_otp": "परतून OTP धाडात",
        "resend_in": "{seconds} सेकंदांनी परतून धाडात",
        "verify_otp_btn": "OTP तपासात आनी खातें सुरू करात",
        "cancel": "रद्द करात",
        "hello_user": "नमस्कार, {name} 👋",
        "edit_form": "फॉर्म दुरुस्त करात",
        "details_prefix": "📝 बारीकसाण: ",
        "age_chip": "पिराय: {age} वर्सां",
        "category_chip": "वर्ग: {category}",
        "income_chip": "येणावळ: ₹{income}/वर्स ({source})",
        "verified_chip": "तपासणी जाल्ली: {type} (#{number})",
        "verified_chip_no_num": "तपासणी जाल्ली: {type}",
        "profile_completion": "प्रोफायल पुराय: ",
        "suggested_schemes": "तुमच्या खातीर सुचयिल्ल्यो येवजण्यो",
        "refresh_suggestions": "परतून सोधात",
        "no_suggestions": "कसलीच येवजण उपलब्ध ना. प्रोफायल पुराय करात.",
        "view_required_details_btn": "गरजेची माहिती पळयात आनी अर्ज करात",
        "offline_mode_active": "ऑफलायन मोड सुरू आसा",
        "change_language": "भास बदलात",
        "required_details_title": "गरजेची माहिती",
        "why_matches_heading": "ही येवजण तुमच्या खातीर कित्याक योग्य आसा",
        "required_certificates_heading": "गरजेचे दाखले आनी कागदपत्रां",
        "prepare_before_applying": "अर्ज करपा आदी हीं कागदपत्रां तयार दवरात:",
        "badge_required": "गरजेचें",
        "badge_optional": "ऐच्छिक",
        "standard_kyc_note": "सादारण KYC कागदपत्रां गरजेचीं:\n• आधार कार्ड\n• पॅन कार्ड\n• बँक पासबूक\n• फोटो",
        "apply_online_btn": "ऑनलाइन अर्ज करात",
        "redirect_notice": "तुम्का सरकारी पोर्टलाचेर व्हेले जातले",
        "no_portal_url": "वेबसाईट लिंक उपलब्ध ना.",
        "action_plan_title": "अर्ज कार्य येवजण",
        "action_plan_for": "{scheme} खातीर येवजण",
        "administered_by": "कारभार: {ministry}",
        "step_1_title": "पात्रता तपासात",
        "step_1_desc": "पिराय आनी येणावळ सरकारी नियमांक जुळयात.",
        "step_2_title": "कागदपत्रांची वळेरी करात",
        "step_2_desc": "आधार आनी पॅन गोळा करात.",
        "step_3_title": "उरिल्ली अट पुराय करात",
        "step_3_desc": "OCR चे साहाय्यान तपासात.",
        "step_4_title": "पोर्टल उघडाात",
        "step_4_desc": "सरकारी वेबसाईटार वचात.",
        "step_5_title": "अर्ज सबमिट करात",
        "step_5_desc": "नंबर सांबाळून दवरात.",
        "open_verified_portal_btn": "सरकारी पोर्टल उघडाात",
        "profile_form_title": "उद्योजक व्यवसाय प्रोफायल",
        "profile_banner_info": "व्यावसायाची माहिती घालात. AI येवजण सोधतलो.",
        "field_company_name": "१. कंपनीचे नांव",
        "hint_company_name": "देखून: श्री लक्ष्मी टेक्स्टाईल्स",
        "field_business_desc": "२. व्यवसायाची माहिती",
        "hint_business_desc": "देखून: कपड्यांचे उत्पादन",
        "field_business_type": "३. व्यवसायाचो प्रकार",
        "field_state": "४. राज्य",
        "field_age": "५. उद्योजकाची पिराय",
        "hint_age": "पिराय",
        "field_annual_income": "६. वर्सुकी येणावळ (₹)",
        "hint_annual_income": "वर्साची येणावळ",
        "field_income_source": "७. येणावळीचो मुखेल मार्ग",
        "field_category_caste": "८. सामाजिक वर्ग / जात",
        "field_certificate_section": "९. दाखलो नंबर (गरजेचो)",
        "certificate_section_desc": "सबसिडी खातीर दाखलो नंबर घालात.",
        "select_cert_type": "दाखल्याचो प्रकार वोंचात",
        "cert_linked": "जोडिल्लो दाखलो: ",
        "btn_save_profile": "प्रोफायल सांबाळात आनी येवजण्यो पळयात ->",
        "field_custom_business_type": "व्यवसायाचो प्रकार लिहात",
        "hint_custom_business_type": "देखून: ड्रोन सेवा",
        "field_custom_state": "राज्य / केंद्रशासित प्रदेश",
        "hint_custom_state": "देखून: गोंय, महाराष्ट्र",
        "field_custom_caste": "जातीचे नांव घालात",
        "hint_custom_caste": "देखून: गावडो, वेळीप आदी",
        "view_all_languages": "सगळ्यो २३ भासो पळयात ->",
        "last_date": "निमाणे तारीख",
        "calc_title": "येवजण रीण आनी EMI कॅल्क्युलेटर",
        "calc_presets_heading": "नांवाजिल्ल्यो येवजण्यो:",
        "calc_loan_amount_label": "गरजेचे रीण:",
        "calc_interest_rate_label": "व्याज दर (%):",
        "calc_moratorium_label": "सवलतीचा काळ (म्हयने):",
        "calc_tenure_label": "एकूण परतफेडीचा काळ:",
        "calc_subsidy_pct_label": "सरकारी अनुदान (%):",
        "calc_monthly_emi": "दर म्हयन्याची EMI",
        "calc_moratorium_monthly": "सवलतीच्या काळांतली EMI",
        "calc_subsidy_credit": "अनुदानाची रक्कम",
        "calc_gross_loan": "एकूण रीण:",
        "calc_net_loan": "उरिल्ले रीण:",
        "calc_total_interest": "एकूण व्याज:",
        "calc_total_outflow": "एकूण दिवपाची रक्कम:",
        "months_suffix": "म्हयने",
        "months_grace": "म्हयने सवलत",
        "partner_locator_title": "लागींचे बँक आनी भागीदार",
        "live_gps": "लाइव्ह GPS",
        "gps_update": "GPS रिफ्रेश करात",
        "partners_found": "भागीदार मेळले",
        "eligible_healthy": "योग्य आनी सकीय",
        "get_directions": "नकाशाचेर वाट पळयात",
        "routing_disabled": "वाट बंद (चड NPA)",
        "calculate_emi": "EMI काढाात",
        "locate_partner": "भागीदार सोधात"
    },
    "ks": {
        "select_your_language": "پنہنہ پسندس زبان ژارِو",
        "select_language_subtitle": "سأرس ایپھس منز استعمال کرنے باپتھ زبان ژارِو:",
        "welcome_header": "SchemeMate AI منز خوش آمدید",
        "welcome_subheading": "پنہنس کاروبار باپتھ سرکاری سکیمہ تہ قرضہ پنہنس زبانِ منز لبِو۔",
        "feature_ai_matching": "شخصی سکیم ژارُن",
        "feature_ai_matching_desc": "کاروبار، ونس تہ زاتِ مطابق صحیح سکیم ژارُن۔",
        "feature_docs": "ضروری کاغذاتن ہنز فہرست",
        "feature_docs_desc": "درخواست دِنہٕ برونہہ ضروری سرٹیفکیٹ۔",
        "feature_portal": "سرکاری پورٹل لنک",
        "feature_portal_desc": "سرکاری پورٹلس تام آسان رسائی۔",
        "btn_create_account": "نواں اکاؤنٹ بناوِو / رجسٹر کرو",
        "btn_login": "لاگ ان کرو",
        "btn_continue": "جاری تھاوو",
        "btn_demo_login": "ڈیمو لاگ ان (ramesh@example.com)",
        "login_title": "SchemeMate AI لاگ ان",
        "create_account_title": "نواں اکاؤنٹ بناوِو",
        "tab_login": "لاگ ان",
        "tab_create_account": "اکاؤنٹ بناوِو",
        "registered_email": "ای میل پتہ",
        "email_hint": "مثلاً: name@example.com",
        "password": "پاس ورڈ",
        "password_hint": "پاس ورڈ درج کرو",
        "password_min_hint": "کم از کم 6 حروف",
        "full_name": "پورا ناو",
        "full_name_hint": "مثلاً: رمیش کمار",
        "phone_number": "فون نمبر",
        "phone_hint": "10 ہندسوں کا نمبر",
        "btn_login_submit": "لاگ ان کرو",
        "btn_register_submit": "اکاؤنٹ بناوِو تہ OTP حاصل کرو",
        "otp_title": "OTP تصدیق کرو",
        "otp_subtitle": "ای میل پر بھیجا گیا 6 ہندسوں کا کوڈ:",
        "resend_otp": "دوبارہ بھیجو",
        "resend_in": "{seconds} سیکنڈ میں",
        "verify_otp_btn": "تصدیق کرو",
        "cancel": "منسوخ",
        "hello_user": "آداب، {name} 👋",
        "edit_form": "فارم میں تبدیلی",
        "details_prefix": "📝 تفصیل: ",
        "age_chip": "عمر: {age} وری",
        "category_chip": "زمرہ: {category}",
        "income_chip": "آمدنی: ₹{income}/وری ({source})",
        "verified_chip": "مصدقہ: {type} (#{number})",
        "verified_chip_no_num": "مصدقہ: {type}",
        "profile_completion": "پروفائل: ",
        "suggested_schemes": "تہندِ باپتھ سکیمہ",
        "refresh_suggestions": "تازہ کرو",
        "no_suggestions": "کانہہ سکیم چھنہٕ۔",
        "view_required_details_btn": "تفصیلات وچھِو تہ درخواست دِو",
        "offline_mode_active": "آف لائن موڈ",
        "change_language": "زبان تبدیل کرو",
        "required_details_title": "ضروری تفصیل",
        "why_matches_heading": "یہ سکیم کیازِ چھِ صحیح",
        "required_certificates_heading": "ضروری کاغذات",
        "prepare_before_applying": "درخواست دِنہٕ برونہہ تیار تھاوو:",
        "badge_required": "ضروری",
        "badge_optional": "اختیاری",
        "standard_kyc_note": "بنیادی KYC کاغذات:\n• آدھار کارڈ\n• پین کارڈ\n• پاس بک\n• فوٹو",
        "apply_online_btn": "آن لائن درخواست دِو",
        "redirect_notice": "تہیہ ییہِ سرکاری پورٹلس پٹھ ننے۔",
        "no_portal_url": "کانہہ لنک چھنہٕ۔",
        "action_plan_title": "طریقہ کار",
        "action_plan_for": "{scheme} باپتھ پلان",
        "administered_by": "وزارت: {ministry}",
        "step_1_title": "اہلیت چیک کرو",
        "step_1_desc": "عمر تہ آمدنی چیک کرو۔",
        "step_2_title": "کاغذات تیار کرو",
        "step_2_desc": "آدھار تہ پین جمع کرو۔",
        "step_3_title": "باقی مکمل کرو",
        "step_3_desc": "اسکین کرو۔",
        "step_4_title": "پورٹل کھولِو",
        "step_4_desc": "سرکاری پورٹلس پٹھ گژھِو۔",
        "step_5_title": "جمع کرو",
        "step_5_desc": "نمبر محفوظ تھاوو۔",
        "open_verified_portal_btn": "سرکاری پورٹل کھولِو",
        "profile_form_title": "کاروباری پروفائل",
        "profile_banner_info": "تفصیل درج کرو۔ AI لبی سکیمہ۔",
        "field_company_name": "1. کمپنی کا ناو",
        "hint_company_name": "مثلاً: شری لکشمی",
        "field_business_desc": "2. کاروبار کی تفصیل",
        "hint_business_desc": "مثلاً: کپڑوں کا کام",
        "field_business_type": "3. قسم",
        "field_state": "4. ریاست",
        "field_age": "5. عمر",
        "hint_age": "عمر",
        "field_annual_income": "6. سالانہ آمدنی (₹)",
        "hint_annual_income": "آمدنی",
        "field_income_source": "7. ذریعہ",
        "field_category_caste": "8. زمرہ",
        "field_certificate_section": "9. سرٹیفکیٹ نمبر",
        "certificate_section_desc": "نمبر درج کرو۔",
        "select_cert_type": "قسم ژارِو",
        "cert_linked": "منسلک: ",
        "btn_save_profile": "محفوظ کرو ->",
        "field_custom_business_type": "قسم درج کرو",
        "hint_custom_business_type": "مثلاً: ڈرون کام",
        "field_custom_state": "ریاست درج کرو",
        "hint_custom_state": "مثلاً: جموں و کشمیر",
        "field_custom_caste": "ذات درج کرو",
        "hint_custom_caste": "مثلاً: بٹ، میر وغیرہ",
        "view_all_languages": "تمام 23 زبانیں وچھِو ->",
        "last_date": "آخری تاریخ",
        "calc_title": "لون تہ EMI کیلکولیٹر",
        "calc_presets_heading": "سکیمہ:",
        "calc_loan_amount_label": "قرضہ:",
        "calc_interest_rate_label": "سود (%):",
        "calc_moratorium_label": "مہلت (ریتھ):",
        "calc_tenure_label": "وقت:",
        "calc_subsidy_pct_label": "سبسیڈی (%):",
        "calc_monthly_emi": "ہر ریتھچ EMI",
        "calc_moratorium_monthly": "مہلتچ EMI",
        "calc_subsidy_credit": "سبسیڈی رقم",
        "calc_gross_loan": "کل قرضہ:",
        "calc_net_loan": "باقی قرضہ:",
        "calc_total_interest": "کل سود:",
        "calc_total_outflow": "کل رقم:",
        "months_suffix": "ریتھ",
        "months_grace": "ریتھ مہلت",
        "partner_locator_title": "قریبی بینک",
        "live_gps": "لائیو GPS",
        "gps_update": "تازہ کرو",
        "partners_found": "بینک لبے",
        "eligible_healthy": "اہل",
        "get_directions": "واٹھ وچھِو",
        "routing_disabled": "واٹھ بند",
        "calculate_emi": "EMI حساب کرو",
        "locate_partner": "بینک لبِو"
    },
    "mai": {
        "select_your_language": "अपने मनपसंद भाषा चुनू",
        "select_language_subtitle": "सभटा ऐप मे प्रयोग लेल अपन भाषा चुनू:",
        "welcome_header": "SchemeMate AI मे स्वागत अछि",
        "welcome_subheading": "अहाँक व्यापार लेल उपयुक्त सरकारी योजना, सब्सिडी आ ऋण सुविधा अपन मातृभाषा मे खोजू।",
        "feature_ai_matching": "व्यक्तिगत योजना चयन",
        "feature_ai_matching_desc": "व्यापार, उमर आ जाति के आधार पर योजना के चुनाव।",
        "feature_docs": "आवश्यक कागजात के सूची",
        "feature_docs_desc": "आवेदन करब सँ पहिले जरूरी प्रमाणपत्र के स्पष्ट सूची।",
        "feature_portal": "सरकारी पोर्टल के सीधा लिंक",
        "feature_portal_desc": "सरकारी वेबसाइट पर एक क्लिक मे सुरक्षित पहुँच।",
        "btn_create_account": "नया खाता बनाऊ / रजिस्टर करू",
        "btn_login": "अपन खाता मे लॉगिन करू",
        "btn_continue": "पंजीकरण जारी राखू",
        "btn_demo_login": "डेमो लॉगिन (ramesh@example.com)",
        "login_title": "SchemeMate AI लॉगिन",
        "create_account_title": "नया खाता बनाऊ",
        "tab_login": "लॉगिन",
        "tab_create_account": "खाता बनाऊ",
        "registered_email": "पंजीकृत ईमेल पता",
        "email_hint": "जैसे: name@example.com",
        "password": "पासवर्ड",
        "password_hint": "अपन पासवर्ड दियू",
        "password_min_hint": "कम सँ कम ६ अक्षर",
        "full_name": "पूरा नाम",
        "full_name_hint": "जैसे: रमेश कुमार",
        "phone_number": "फोन नंबर",
        "phone_hint": "১০-अंकी मोबाइल नंबर",
        "btn_login_submit": "लॉगिन करू",
        "btn_register_submit": "खाता बनाऊ आ OTP पाओ",
        "otp_title": "ईमेल OTP सत्यापित करू",
        "otp_subtitle": "ईमेल पर भेजल गेल ६-अंकी कोड दियू:",
        "resend_otp": "पुनः OTP भेजूं",
        "resend_in": "{seconds} सेकंड मे",
        "verify_otp_btn": "OTP जांचू आ खाता चालू करू",
        "cancel": "रद्द करू",
        "hello_user": "प्रणाम, {name} 👋",
        "edit_form": "फॉर्म बदलो",
        "details_prefix": "📝 विवरण: ",
        "age_chip": "उमर: {age} वर्ष",
        "category_chip": "वर्ग: {category}",
        "income_chip": "आय: ₹{income}/वर्ष ({source})",
        "verified_chip": "प्रमाणित: {type} (#{number})",
        "verified_chip_no_num": "प्रमाणित: {type}",
        "profile_completion": "प्रोफाइल पूरा: ",
        "suggested_schemes": "अहाँक लेल सुझायल गेल योजना",
        "refresh_suggestions": "रिफ्रेश करू",
        "no_suggestions": "कोई योजना उपलब्ध नहि अछि। प्रोफाइल पूरा करू।",
        "view_required_details_btn": "ज़रूरी विवरण देखू आ आवेदन करू",
        "offline_mode_active": "ऑफलाइन मोड चालू अछि",
        "change_language": "भाषा बदलू",
        "required_details_title": "ज़रूरी विवरण",
        "why_matches_heading": "ई योजना अहाँक लेल किअक सही अछि",
        "required_certificates_heading": "ज़रूरी प्रमाणपत्र आ कागजात",
        "prepare_before_applying": "आवेदन करब सँ पहिले ई तैयार राखू:",
        "badge_required": "अनिवार्य",
        "badge_optional": "ऐच्छिक",
        "standard_kyc_note": "साधारण KYC कागजात ज़रूरी:\n• आधार कार्ड\n• पैन कार्ड\n• बैंक पासबुक\n• फोटो",
        "apply_online_btn": "ऑनलाइन आवेदन करू",
        "redirect_notice": "अहाँ केँ सरकारी वेबसाइट पर लए जायल जायत",
        "no_portal_url": "कोनो सरकारी लिंक नहि अछि।",
        "action_plan_title": "आवेदन कार्य योजना",
        "action_plan_for": "{scheme} लेल योजना",
        "administered_by": "प्रशासन: {ministry}",
        "step_1_title": "पात्रता जांचू",
        "step_1_desc": "उमर आ आय नियम सँ मिलाऊ।",
        "step_2_title": "कागजात सूची बनाऊ",
        "step_2_desc": "आधार आ पैन जमा करू।",
        "step_3_title": "पूरा करू",
        "step_3_desc": "OCR सँ जांच करू।",
        "step_4_title": "वेबसाइट खोलू",
        "step_4_desc": "सरकारी पोर्टल पर जाऊ।",
        "step_5_title": "जमा करू आ ट्रैक करू",
        "step_5_desc": "नंबर संभालि कए राखू।",
        "open_verified_portal_btn": "सरकारी पोर्टल खोलू",
        "profile_form_title": "व्यापारिक प्रोफाइल",
        "profile_banner_info": "व्यापार के विवरण दियू। AI योजना खोजत।",
        "field_company_name": "१. कंपनी के नाम",
        "hint_company_name": "जैसे: श्री लक्ष्मी टेक्सटाइल",
        "field_business_desc": "२. व्यापार के विवरण",
        "hint_business_desc": "जैसे: कपड़ा निर्माण आ बिक्री",
        "field_business_type": "३. व्यापार के प्रकार",
        "field_state": "४. राज्य",
        "field_age": "५. व्यापारी के उमर",
        "hint_age": "उमर",
        "field_annual_income": "६. सालाना आय (₹)",
        "hint_annual_income": "सालाना आय",
        "field_income_source": "७. आय के जरिया",
        "field_category_caste": "८. सामाजिक वर्ग / जाति",
        "field_certificate_section": "९. प्रमाणपत्र नंबर (ज़रूरी)",
        "certificate_section_desc": "सब्सिडी लेल प्रमाणपत्र नंबर दियू।",
        "select_cert_type": "प्रमाणपत्र चुनू",
        "cert_linked": "जुड़ल प्रमाणपत्र: ",
        "btn_save_profile": "प्रोफाइल संभालू आ योजना देखू ->",
        "field_custom_business_type": "व्यापार के प्रकार लिखू",
        "hint_custom_business_type": "जैसे: ड्रोन सेवा",
        "field_custom_state": "राज्य / केंद्र शासित प्रदेश",
        "hint_custom_state": "जैसे: बिहार, झारखंड",
        "field_custom_caste": "जाति के नाम दियू",
        "hint_custom_caste": "जैसे: मैथिल ब्राह्मण, झा, यादव आदि",
        "view_all_languages": "सभटा २३ भाषा देखू ->",
        "last_date": "अंतिम तारीख",
        "calc_title": "योजना कर्जा आ EMI कैलकुलेटर",
        "calc_presets_heading": "प्रसिद्ध योजना:",
        "calc_loan_amount_label": "ज़रूरी कर्जा:",
        "calc_interest_rate_label": "ब्याज दर (%):",
        "calc_moratorium_label": "छूट के समय (महीना):",
        "calc_tenure_label": "कुल वापस मोड़ब के समय:",
        "calc_subsidy_pct_label": "सरकारी सब्सिडी (%):",
        "calc_monthly_emi": "महीना के EMI",
        "calc_moratorium_monthly": "छूट के समय के EMI",
        "calc_subsidy_credit": "सब्सिडी के रकम",
        "calc_gross_loan": "कुल कर्जा:",
        "calc_net_loan": "बाकी कर्जा:",
        "calc_total_interest": "कुल ब्याज:",
        "calc_total_outflow": "कुल देबए वाला रकम:",
        "months_suffix": "महीना",
        "months_grace": "महीना छूट",
        "partner_locator_title": "नजदीकी बैंक आ साझेदार",
        "live_gps": "लाइव GPS",
        "gps_update": "GPS ताजा करू",
        "partners_found": "साझेदार भेटल",
        "eligible_healthy": "सही आ सक्रिय",
        "get_directions": "नक्शा पर रास्ता देखू",
        "routing_disabled": "रास्ता बंद (बेसी NPA)",
        "calculate_emi": "EMI निकालू",
        "locate_partner": "साझेदार खोजू"
    },
    "mni": {
        "select_your_language": "નહાંગી પંબા લોન ખોયબ્યુ",
        "select_language_subtitle": "એપ્લિકેશનદા શીજિન્નનબા લોન ખોયબ્યુ:",
        "welcome_header": "SchemeMate AI દા તરામના ઓકચરી",
        "welcome_subheading": "લલોન-ઈતિકગી સરકારી સ્કીમ અマスુંગ સેનથ્રાંગ ઈશાગી લોનદા થીબિયુ।",
        "feature_ai_matching": "ઈશાગી સ્કીમ ખોયબા",
        "feature_ai_matching_desc": "લલોન-ઈતિક, ચહી અマスુંગ જાતિગી મતુંગ ઈન્ના સ્કીમ ખોયબી।",
        "feature_docs": "ચાઈશ્રી-ચેચાંગ ગાઈડ",
        "feature_docs_desc": "દરખાસ પિદ્રિગેઈ મમાંગદા ચાંગબામ ચેચાંગશીંગ।",
        "feature_portal": "સરકારી પોર્ટલ લિંક",
        "feature_portal_desc": "સરકારી પોર્ટલદા થુના ચાંગબા।",
        "btn_create_account": "અનોબ્બા એકાઉન્ટ શેમ્બ્યુ",
        "btn_login": "લોગઈન તૌબ્યુ",
        "btn_continue": "મખા તાબ્યુ",
        "btn_demo_login": "ડેમો લોગઈન (ramesh@example.com)",
        "login_title": "SchemeMate AI લોગઈન",
        "create_account_title": "અનોબ્બા એકાઉન્ટ શેમ્બ્યુ",
        "tab_login": "લોગઈન",
        "tab_create_account": "એકાઉન્ટ શેમ્બ્યુ",
        "registered_email": "ઈમેલ લીફમ",
        "email_hint": "જેરાઈ: name@example.com",
        "password": "પાસવર્ડ",
        "password_hint": "પાસવર્ડ નમબ્યુ",
        "password_min_hint": "મયામદા ૬ મયુએક",
        "full_name": "અપુન્બા મમિંગ",
        "full_name_hint": "જેરાઈ: રમેશ કુમાર",
        "phone_number": "ફોન નમ્બર",
        "phone_hint": "૧૦ મયુએક ફોન",
        "btn_login_submit": "લોગઈન તૌબ્યુ",
        "btn_register_submit": "એકાઉન્ટ શેમ્બ્યુ અマスુંગ OTP લૌબ્યુ",
        "otp_title": "OTP ચેક તૌબ્યુ",
        "otp_subtitle": "ઈમેલદા થારકપ્પા ૬ મયુએક નમબ્યુ:",
        "resend_otp": "અમુના થારકઉ",
        "resend_in": "{seconds} સેકન્ડદા",
        "verify_otp_btn": "OTP ચેક તૌબ્યુ",
        "cancel": "કાકથોકબ્યુ",
        "hello_user": "ખુરુમજરી, {name} 👋",
        "edit_form": "ફોર્મ હોંગબ્યુ",
        "details_prefix": "📝 મચાંગ: ",
        "age_chip": "ચહી: {age}",
        "category_chip": "કાંગલુપ: {category}",
        "income_chip": "તાનબા: ₹{income}/ચહી ({source})",
        "verified_chip": "ચેક તૌરબ્બા: {type} (#{number})",
        "verified_chip_no_num": "ચેક તૌરબ્બા: {type}",
        "profile_completion": "પ્રોફાઈલ લોઈશિનબા: ",
        "suggested_schemes": "નાગી સ્કીમશીંગ",
        "refresh_suggestions": "અમુક ઈહાંગ હાંગબ્યુ",
        "no_suggestions": "સ્કીમ લેઈતે।",
        "view_required_details_btn": "મચાંગ યેન્ગબ્યુ અマスુંગ અપ્લાઈ તૌબ્યુ",
        "offline_mode_active": "ઓફલાઈન મોડદા લેઈ",
        "change_language": "લોન હોંગબ્યુ",
        "required_details_title": "ચાંગબામ મચાંગ",
        "why_matches_heading": "સ્કીમ અસી નાગી ચાપ્ચાબ્બા",
        "required_certificates_heading": "ચાંગબામ ચેચાંગશીંગ",
        "prepare_before_applying": "દરખાસ પિદ્રિગેઈ મમાંગદા શেম্ব્યુ:",
        "badge_required": "ચાઈતે યાબ્રા",
        "badge_optional": "યાબ્રા",
        "standard_kyc_note": "KYC ચેચાંગશીંગ:\n• આધાર કાડ\n• પાન કાડ\n• બેંક પાસબુક\n• ફોટો",
        "apply_online_btn": "ઓનલાઈન અપ્લાઈ તૌબ્યુ",
        "redirect_notice": "સરકારી પોર્ટલદા ચત્તોગની",
        "no_portal_url": "લિંક લેઈતે।",
        "action_plan_title": "થૌરાંગ ફારિલાઈ",
        "action_plan_for": "{scheme} ગી થૌરાંગ",
        "administered_by": "મંત્રીલય: {ministry}",
        "step_1_title": "ચેક તૌબ્યુ",
        "step_1_desc": "ચહી અマスુંગ તાનબા યેન્ગબ્યુ।",
        "step_2_title": "ચેચાંગ પુન્શિનબ્યુ",
        "step_2_desc": "આધાર અマスુંગ પાન કાડ લૌબ્યુ।",
        "step_3_title": "લોઈશિનબ્યુ",
        "step_3_desc": "સ્કેન તૌબ્યુ।",
        "step_4_title": "પોર્ટલ હાંગબ્યુ",
        "step_4_desc": "વેબસાઈટદા ચત્તૌ।",
        "step_5_title": "પિશનબ્યુ",
        "step_5_desc": "નમ્બર થમબ્યુ।",
        "open_verified_portal_btn": "સરકારી પોર્ટલ હાંગબ્યુ",
        "profile_form_title": "લલોન-ઈતિક પ્રોફાઈલ",
        "profile_banner_info": "મચાંગ નમબ્યુ। AI ના સ્કીમ થિગની।",
        "field_company_name": "૧. કંપની મમિંગ",
        "hint_company_name": "જેરાઈ: શ્રી લક્ષ્મી",
        "field_business_desc": "૨. લલોન-ઈતિક મચાંગ",
        "hint_business_desc": "જેરાઈ: ફી શાબ્બા",
        "field_business_type": "૩. મખાલ",
        "field_state": "૪. સ્ટેટ",
        "field_age": "૫. ચહી",
        "hint_age": "ચહી",
        "field_annual_income": "૬. ચહીગી તાનબા (₹)",
        "hint_annual_income": "તાનબા",
        "field_income_source": "૭. તાનબગી લામ્બી",
        "field_category_caste": "૮. કાંગલુપ",
        "field_certificate_section": "૯. ચેચાંગ નમ્બર",
        "certificate_section_desc": "નમ્બર નમબ્યુ।",
        "select_cert_type": "મખાલ ખોયબ્યુ",
        "cert_linked": "શમન્નબ્બા: ",
        "btn_save_profile": "પ્રોફાઈલ થમબ્યુ ->",
        "field_custom_business_type": "મખાલ ઈબ્યુ",
        "hint_custom_business_type": "જેરાઈ: ડ્રોન થૌબાગી",
        "field_custom_state": "સ્ટેટ ઈબ્યુ",
        "hint_custom_state": "જેરાઈ: મણિપુર",
        "field_custom_caste": "જાતિ ઈબ્યુ",
        "hint_custom_caste": "જેરાઈ: મૈતૈ આદિ",
        "view_all_languages": "લોન ૨૩ મયામ યેન્ગબ્યુ ->",
        "last_date": "આરોઇબા તારિખ",
        "calc_title": "લોન અマスુંગ EMI કેલ્ક્યુલેટર",
        "calc_presets_heading": "સ્કીમશીંગ:",
        "calc_loan_amount_label": "ચાંગબામ લોન:",
        "calc_interest_rate_label": "સૂદ (%):",
        "calc_moratorium_label": "મોરેટોરિયમ (થા):",
        "calc_tenure_label": "પુન્ના મતાંગ:",
        "calc_subsidy_pct_label": "સરકારી સબસિડી (%):",
        "calc_monthly_emi": "થાગી EMI",
        "calc_moratorium_monthly": "મોરેટોરિયમ થાગી",
        "calc_subsidy_credit": "સબસિડી સેનથ્રાંગ",
        "calc_gross_loan": "અપુન્બા લોન:",
        "calc_net_loan": "લેન્હોબ્બા લોન:",
        "calc_total_interest": "અપુન્બા સૂદ:",
        "calc_total_outflow": "પિગદબ્બા શેલ:",
        "months_suffix": "થા",
        "months_grace": "થા કોહતબ્બા",
        "partner_locator_title": "નાકશિબ્બા બેંક",
        "live_gps": "લાઈવ GPS",
        "gps_update": "GPS નૌના હાંગબ્યુ",
        "partners_found": "બેંક ફંગબ્રે",
        "eligible_healthy": "યાબ્બા",
        "get_directions": "લંબેલ યેન્ગબ્યુ",
        "routing_disabled": "લંબેલ થિંગબ્રે",
        "calculate_emi": "EMI હિસાબ તૌબ્યુ",
        "locate_partner": "બેંક થીબ્યુ"
    },
    "ne": {
        "select_your_language": "आफ्नो मनपर्ने भाषा छान्नुहोस्",
        "select_language_subtitle": "पूरा एपमा प्रयोग गर्न आफ्नो भाषा छान्नुहोस्:",
        "welcome_header": "SchemeMate AI मा स्वागत छ",
        "welcome_subheading": "आफ्नो व्यवसायका लागि उपयुक्त सरकारी योजना, अनुदान र ऋण सुविधा आफ्नै भाषामा खोज्नुहोस्।",
        "feature_ai_matching": "व्यक्तिगत योजना छनोट",
        "feature_ai_matching_desc": "व्यवसाय, उमेर र जातिका आधारमा सही योजनाको छनोट।",
        "feature_docs": "आवश्यक कागजातको सूची",
        "feature_docs_desc": "आवेदन दिनुअघि आवश्यक प्रमाणपत्रहरूको स्पष्ट सूची।",
        "feature_portal": "सरकारी पोर्टलको सीधा लिङ्क",
        "feature_portal_desc": "सरकारी वेबसाइटमा एक क्लिकमा सुरक्षित पहुँच।",
        "btn_create_account": "नयाँ खाता बनाउनुहोस् / दर्ता गर्नुहोस्",
        "btn_login": "आफ्नो खातामा लगइन गर्नुहोस्",
        "btn_continue": "दर्ता जारी राख्नुहोस्",
        "btn_demo_login": "डेमो लगइन (ramesh@example.com)",
        "login_title": "SchemeMate AI लगइन",
        "create_account_title": "नयाँ खाता बनाउनुहोस्",
        "tab_login": "लगइन",
        "tab_create_account": "खाता बनाउनुहोस्",
        "registered_email": "दर्ता गरिएको इमेल ठेगाना",
        "email_hint": "जस्तै: name@example.com",
        "password": "पासवर्ड",
        "password_hint": "आफ्नो पासवर्ड राख्नुहोस्",
        "password_min_hint": "कमसेकम ६ वटा अक्षर",
        "full_name": "पूरा नाम",
        "full_name_hint": "जस्तै: रमेश कुमार",
        "phone_number": "फोन नम्बर",
        "phone_hint": "१०-अङ्कको मोबाइल नम्बर",
        "btn_login_submit": "लगइन गर्नुहोस्",
        "btn_register_submit": "खाता बनाउनुहोस् र OTP पाउनुहोस्",
        "otp_title": "इमेल OTP जाँच्नुहोस्",
        "otp_subtitle": "इमेलमा पठाइएको ६-अङ्कको कोड राख्नुहोस्:",
        "resend_otp": "पुनः OTP पठाउनुहोस्",
        "resend_in": "{seconds} सेकेन्डमा",
        "verify_otp_btn": "OTP जाँच्नुहोस् र खाता सक्रिय गर्नुहोस्",
        "cancel": "रद्द गर्नुहोस्",
        "hello_user": "नमस्ते, {name} 👋",
        "edit_form": "फर्म सम्पादन गर्नुहोस्",
        "details_prefix": "📝 विवरण: ",
        "age_chip": "उमेर: {age} वर्ष",
        "category_chip": "वर्ग: {category}",
        "income_chip": "आय: ₹{income}/वर्ष ({source})",
        "verified_chip": "प्रमाणित: {type} (#{number})",
        "verified_chip_no_num": "प्रमाणित: {type}",
        "profile_completion": "प्रोफाइल पूरा: ",
        "suggested_schemes": "तपाईंका लागि सिफारिस गरिएका योजनाहरू",
        "refresh_suggestions": "ताजा गर्नुहोस्",
        "no_suggestions": "कुनै योजना उपलब्ध छैन। प्रोफाइल पूरा गर्नुहोस्।",
        "view_required_details_btn": "आवश्यक विवरण हेर्नुहोस् र आवेदन दिनुहोस्",
        "offline_mode_active": "अफलाइन मोड सक्रिय छ",
        "change_language": "भाषा फेर्नुहोस्",
        "required_details_title": "आवश्यक विवरण",
        "why_matches_heading": "यो योजना तपाईंका लागि किन सही छ",
        "required_certificates_heading": "आवश्यक प्रमाणपत्र र कागजातहरू",
        "prepare_before_applying": "आवेदन दिनुअघि यी तयार राख्नुहोस्:",
        "badge_required": "अनिवार्य",
        "badge_optional": "ऐच्छिक",
        "standard_kyc_note": "साधारण KYC कागजात आवश्यक:\n• आधार कार्ड\n• प्यान कार्ड\n• बैंक पासबुक\n• फोटो",
        "apply_online_btn": "अनलाइन आवेदन दिनुहोस्",
        "redirect_notice": "तपाईंलाई सरकारी वेबसाइटमा लगिनेछ",
        "no_portal_url": "कुनै लिङ्क उपलब्ध छैन।",
        "action_plan_title": "आवेदन कार्य योजना",
        "action_plan_for": "{scheme} का लागि योजना",
        "administered_by": "प्रशासन: {ministry}",
        "step_1_title": "पात्रता जाँच्नुहोस्",
        "step_1_desc": "उमेर र आय नियमसँग मिलाउनुहोस्।",
        "step_2_title": "कागजात सूची बनाउनुहोस्",
        "step_2_desc": "आधार र प्यान सङ्कलन गर्नुहोस्।",
        "step_3_title": "पूरा गर्नुहोस्",
        "step_3_desc": "OCR बाट जाँच्नुहोस्।",
        "step_4_title": "वेबसाइट खोल्नुहोस्",
        "step_4_desc": "सरकारी पोर्टलमा जानुहोस्।",
        "step_5_title": "बुझाउनुहोस् र ट्र्याक गर्नुहोस्",
        "step_5_desc": "नम्बर सुरक्षित राख्नुहोस्।",
        "open_verified_portal_btn": "सरकारी पोर्टल खोल्नुहोस्",
        "profile_form_title": "व्यापारिक प्रोफाइल",
        "profile_banner_info": "व्यापारको विवरण राख्नुहोस्। AI ले योजना खोज्नेछ।",
        "field_company_name": "१. कम्पनीको नाम",
        "hint_company_name": "जस्तै: श्री लक्ष्मी टेक्सटाइल",
        "field_business_desc": "२. व्यापारको विवरण",
        "hint_business_desc": "जस्तै: कपडा उत्पादन र बिक्री",
        "field_business_type": "३. व्यापारको प्रकार",
        "field_state": "४. राज्य",
        "field_age": "५. व्यापारीको उमेर",
        "hint_age": "उमेर",
        "field_annual_income": "६. वार्षिक आय (₹)",
        "hint_annual_income": "वार्षिक आय",
        "field_income_source": "७. आयको स्रोत",
        "field_category_caste": "८. सामाजिक वर्ग / जाति",
        "field_certificate_section": "९. प्रमाण पत्र नम्बर (अनिवार्य)",
        "certificate_section_desc": "अनुदानका लागि प्रमाण पत्र नम्बर राख्नुहोस्।",
        "select_cert_type": "प्रमाण पत्र छान्नुहोस्",
        "cert_linked": "जोडिएको प्रमाण पत्र: ",
        "btn_save_profile": "प्रोफाइल सुरक्षित गर्नुहोस् ->",
        "field_custom_business_type": "व्यापारको प्रकार लेख्नुहोस्",
        "hint_custom_business_type": "जस्तै: ड्रोन सेवा",
        "field_custom_state": "राज्य / केन्द्र शासित प्रदेश",
        "hint_custom_state": "जस्तै: सिक्किम, पश्चिम बङ्गाल",
        "field_custom_caste": "जातिको नाम लेख्नुहोस्",
        "hint_custom_caste": "जस्तै: क्षेत्री, बाहुन, गुरुङ आदि",
        "view_all_languages": "सबै २३ भाषा हेर्नुहोस् ->",
        "last_date": "अन्तिम मिति",
        "calc_title": "योजना ऋण र EMI क्याल्कुलेटर",
        "calc_presets_heading": "लोकप्रिय योजनाहरू:",
        "calc_loan_amount_label": "आवश्यक ऋण:",
        "calc_interest_rate_label": "ब्याज दर (%):",
        "calc_moratorium_label": "छुटको समय (महिना):",
        "calc_tenure_label": "कुल फिर्ता गर्ने समय:",
        "calc_subsidy_pct_label": "सरकारी अनुदान (%):",
        "calc_monthly_emi": "महिनाको EMI",
        "calc_moratorium_monthly": "छुटको समयको EMI",
        "calc_subsidy_credit": "अनुदानको रकम",
        "calc_gross_loan": "कुल ऋण:",
        "calc_net_loan": "बाँकी ऋण:",
        "calc_total_interest": "कुल ब्याज:",
        "calc_total_outflow": "कुल तिर्नुपर्ने रकम:",
        "months_suffix": "महिना",
        "months_grace": "महिना छुट",
        "partner_locator_title": "नजिकैका बैंक र साझेदारहरू",
        "live_gps": "लाइभ GPS",
        "gps_update": "GPS ताजा गर्नुहोस्",
        "partners_found": "साझेदारहरू भेटिए",
        "eligible_healthy": "सही र सक्रिय",
        "get_directions": "नक्सामा बाटो हेर्नुहोस्",
        "routing_disabled": "बाटो बन्द (उच्च NPA)",
        "calculate_emi": "EMI हिसाब गर्नुहोस्",
        "locate_partner": "साझेदार खोज्नुहोस्"
    },
    "sa": {
        "select_your_language": "स्वेच्छिक भाषां वृणोतु",
        "select_language_subtitle": "सम्पूर्णे उपयोजने उपयोगाय भाषां वृणोतु:",
        "welcome_header": "SchemeMate AI मध्ये स्वागतम्",
        "welcome_subheading": "स्वकीयवाणिज्यस्य कृते सर्वकारीययोजनाः, अनुदानं च स्वभाषायां जानन्तु।",
        "feature_ai_matching": "व्यक्तिगतयोजनाचयनम्",
        "feature_ai_matching_desc": "व्यापारस्य, वयसः, जातेश्च आधारेण योजनाचयनम्।",
        "feature_docs": "आवश्यकलेख्यपत्राणाम् मार्गदर्शिका",
        "feature_docs_desc": "आवेदनपूर्वं आवश्यकप्रमाणपत्राणां स्पष्टसूची।",
        "feature_portal": "सर्वकारपटले साक्षात्सम्बन्धः",
        "feature_portal_desc": "सर्वकारीयजालपुटे सुरक्षितप्रवेशः।",
        "btn_create_account": "नवीनं वृत्तं रचयतु / पञ्जीकरणम्",
        "btn_login": "प्रवेशं करोतु",
        "btn_continue": "अनुवर्तयतु",
        "btn_demo_login": "प्रादर्शिकप्रवेशः (ramesh@example.com)",
        "login_title": "SchemeMate AI प्रवेशः",
        "create_account_title": "नवीनं वृत्तं रचयतु",
        "tab_login": "प्रवेशः",
        "tab_create_account": "वृत्तरचना",
        "registered_email": "पञ्जीकृत-ईमेल-सङ्केतः",
        "email_hint": "यथा: name@example.com",
        "password": "गुप्तशब्दः",
        "password_hint": "गुप्तशब्दं लिखतु",
        "password_min_hint": "न्यूनातिन्यूनम् ६ अक्षराणि",
        "full_name": "पूर्णं नाम",
        "full_name_hint": "यथा: रमेश कुमारः",
        "phone_number": "दूरभाषसङ्ख्या",
        "phone_hint": "१० अङ्कयुक्ता सङ्ख्या",
        "btn_login_submit": "प्रविशतु",
        "btn_register_submit": "वृत्तं रचयित्वा OTP प्राप्नोतु",
        "otp_title": "ईमेल OTP परीक्षताम्",
        "otp_subtitle": "ईमेल-मध्ये प्रेषितं ६ अङ्कयुक्तं कूटं लिखतु:",
        "resend_otp": "पुनः प्रेषयतु",
        "resend_in": "{seconds} क्षणेषु",
        "verify_otp_btn": "सत्याप्य वृत्तं सक्रियं करोतु",
        "cancel": "निरस्यताम्",
        "hello_user": "नमो नमः, {name} 👋",
        "edit_form": "पत्रं संस्करोतु",
        "details_prefix": "📝 विवरणम्: ",
        "age_chip": "वयः: {age} वर्षाणि",
        "category_chip": "वर्गः: {category}",
        "income_chip": "आयः: ₹{income}/वर्षम् ({source})",
        "verified_chip": "सत्यापितम्: {type} (#{number})",
        "verified_chip_no_num": "सत्यापितम्: {type}",
        "profile_completion": "वृत्तपूर्तता: ",
        "suggested_schemes": "भवते अनुशंसिताः योजनाः",
        "refresh_suggestions": "पुनरीक्षताम्",
        "no_suggestions": "कापि योजना नास्ति। वृत्तं पूरयतु।",
        "view_required_details_btn": "विवरणं दृष्ट्वा आवेदयेत्",
        "offline_mode_active": "ऑफलाइन-प्रणाली सक्रिया",
        "change_language": "भाषां परिवर्तयतु",
        "required_details_title": "आवश्यकविवरणम्",
        "why_matches_heading": "इयं योजना किमर्थं योग्या",
        "required_certificates_heading": "आवश्यकप्रमाणपत्राणि लेख्यानि च",
        "prepare_before_applying": "आवेदनावपूर्वं एतानि सज्जीकरोतु:",
        "badge_required": "अनिवार्यम्",
        "badge_optional": "ऐच्छिकम्",
        "standard_kyc_note": "साधारण-KYC लेख्यानि अनिवार्यणि:\n• आधारपत्रम्\n• पैनपत्रम्\n• बैंक-पासबुक\n• चित्रम्",
        "apply_online_btn": "ऑनलाइन-माध्यमेन आवेदयेत्",
        "redirect_notice": "भवन्तः सर्वकारपटले नेष्यन्ते",
        "no_portal_url": "कोऽपि सम्बन्धः नास्ति।",
        "action_plan_title": "आवेदन-कार्ययोजना",
        "action_plan_for": "{scheme} अस्य कृते योजना",
        "administered_by": "प्रशासनम्: {ministry}",
        "step_1_title": "पात्रतां परीक्षताम्",
        "step_1_desc": "वयः आयं च नियमैः सह मेलयतु।",
        "step_2_title": "सूचीं रचयतु",
        "step_2_desc": "आधारं पैनपत्रं च एकत्र करोतु।",
        "step_3_title": "पूरयतु",
        "step_3_desc": "OCR द्वारा परीक्षताम्।",
        "step_4_title": "पटलमुद्घाटयतु",
        "step_4_desc": "सर्वकारीयजालपुटं गच्छतु।",
        "step_5_title": "समर्पयतु",
        "step_5_desc": "सङ्ख्यां सुरक्षितां करोतु।",
        "open_verified_portal_btn": "सर्वकारीयपटलमुद्घाटयतु",
        "profile_form_title": "वाणिज्यिकवृत्तम्",
        "profile_banner_info": "व्यापारविवरणं लिखतु। AI योजनां अन्विष्यति।",
        "field_company_name": "१. संस्थायाः नाम",
        "hint_company_name": "यथा: श्री लक्ष्मी टेक्सटाइल्स",
        "field_business_desc": "२. व्यापारस्य विवरणम्",
        "hint_business_desc": "यथा: वस्त्रनिर्माणं विक्रयश्च",
        "field_business_type": "३. व्यापारप्रकारः",
        "field_state": "४. राज्यम्",
        "field_age": "५. उद्यमिनः वयः",
        "hint_age": "वयः",
        "field_annual_income": "६. वार्षिकी आयः (₹)",
        "hint_annual_income": "वार्षिकी आयः",
        "field_income_source": "७. आयस्य स्रोतम्",
        "field_category_caste": "८. सामाजिकवर्गः / जातिः",
        "field_certificate_section": "९. प्रमाणपत्रसङ्ख्या (अनिवार्या)",
        "certificate_section_desc": "अनुदानाय प्रमाणपत्रसङ्ख्यां लिखतु।",
        "select_cert_type": "प्रमाणपत्रं वृणोतु",
        "cert_linked": "सम्बद्धं प्रमाणपत्रम्: ",
        "btn_save_profile": "वृत्तं रक्षित्वा योजनाः पश्यतु ->",
        "field_custom_business_type": "व्यापारप्रकारं लिखतु",
        "hint_custom_business_type": "यथा: द्रोणसेवा",
        "field_custom_state": "राज्यम् / केन्द्रशासितप्रदेशः",
        "hint_custom_state": "यथा: उत्तराखण्डः, हिमाचलः",
        "field_custom_caste": "जातिनाम लिखतु",
        "hint_custom_caste": "यथा: भारद्वाजः, शर्मा इत्यादि",
        "view_all_languages": "सर्वाः २३ भाषाः पश्यतु ->",
        "last_date": "अन्तिमः दिनाङ्कः",
        "calc_title": "योजनाऋणं EMI गणकञ्च",
        "calc_presets_heading": "प्रसिद्धाः योजनाः:",
        "calc_loan_amount_label": "आवश्यकं ऋणम्:",
        "calc_interest_rate_label": "वृद्धिसङ्ख्या (%):",
        "calc_moratorium_label": "सवलतेः कालः (मासाः):",
        "calc_tenure_label": "सम्पूर्णप्रत्यर्पणकालः:",
        "calc_subsidy_pct_label": "सर्वकारीयानुदानम् (%):",
        "calc_monthly_emi": "मासिकी EMI",
        "calc_moratorium_monthly": "सवलतिकालस्य EMI",
        "calc_subsidy_credit": "अनुदानधनम्",
        "calc_gross_loan": "कुलऋणम्:",
        "calc_net_loan": "अवशिष्टऋणम्:",
        "calc_total_interest": "कुलवृद्धिः:",
        "calc_total_outflow": "देयं कुलधनम्:",
        "months_suffix": "मासाः",
        "months_grace": "मासाः सवलतः",
        "partner_locator_title": "समीपस्थाः कोषागाराः सहयोगिनश्च",
        "live_gps": "सजीव-GPS",
        "gps_update": "GPS नवीकरोतु",
        "partners_found": "सहयोगिनः लब्धाः",
        "eligible_healthy": "योग्याः सक्रियाश्च",
        "get_directions": "मानचित्रे मार्गं पश्यतु",
        "routing_disabled": "मार्गः रुद्धः (उच्च-NPA)",
        "calculate_emi": "EMI गणयतु",
        "locate_partner": "सहयोगिनं अन्विष्यतु"
    },
    "sat": {
        "select_your_language": "ᱟᱢᱟᱜ ᱠᱩᱥᱤ ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱟᱣ ᱢᱮ",
        "select_language_subtitle": "ᱜᱚᱴᱟ ᱮᱯ ᱨᱮ ᱵᱮᱣᱦᱟᱨ ᱞᱟᱹᱜᱤᱫ ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱟᱣ ᱢᱮ:",
        "welcome_header": "SchemeMate AI ᱨᱮ ᱥᱟᱹᱜᱩᱱ ᱫᱟᱨᱟᱢ",
        "welcome_subheading": "ᱟᱢᱟᱜ ᱵᱮᱯᱟᱨ ᱞᱟᱹᱜᱤᱫ ᱥᱚᱨᱠᱟᱨᱤ ᱟᱪᱟᱨ, ᱜᱚᱲᱚ ᱟᱨ ᱨᱤᱬ ᱟᱯᱱᱟᱨ ᱯᱟᱹᱨᱥᱤ ᱛᱮ ᱧᱟᱢ ᱢᱮ।",
        "feature_ai_matching": "ᱟᱯᱱᱟᱨ ᱞᱟᱹᱜᱤᱫ ᱥᱠᱤᱢ ᱵᱟᱪᱷᱟᱣ",
        "feature_ai_matching_desc": "ᱵᱮᱯᱟᱨ, ᱩᱢᱮᱨ ᱟᱨ ᱡᱟᱹᱛᱤ ᱞᱮᱠᱟᱛᱮ ᱥᱠᱤᱢ ᱵᱟᱪᱷᱟᱣ।",
        "feature_docs": "ᱞᱟᱹᱠᱛᱤᱭᱟᱱ ᱥᱟᱠᱟᱢ ᱞᱤᱥᱴ",
        "feature_docs_desc": "ᱮᱯᱞᱟᱭ ᱢᱟᱲᱟᱝ ᱞᱟᱹᱠᱛᱤᱭᱟᱱ ᱥᱟᱠᱟᱢ।",
        "feature_portal": "ᱥᱚᱨᱠᱟᱨᱤ ᱯᱚᱨᱴᱟᱞ ᱞᱤᱝᱠ",
        "feature_portal_desc": "ᱥᱚᱨᱠᱟᱨᱤ ᱣᱮᱵᱽᱥᱟᱭᱤᱴ ᱨᱮ ᱥᱩᱨᱚᱠᱷᱤᱛ ᱵᱚᱞᱚᱱ।",
        "btn_create_account": "ᱱᱟᱶᱟ ᱮᱠᱟᱣᱩᱱᱴ ᱵᱮᱱᱟᱣ ᱢᱮ / ᱨᱮᱡᱤᱥᱴᱟᱨ",
        "btn_login": "ᱞᱚᱜᱤᱱ ᱢᱮ",
        "btn_continue": "ᱞᱟᱦᱟ ᱪᱟᱞᱟᱜ ᱢᱮ",
        "btn_demo_login": "ᱰᱮᱢᱚ ᱞᱚᱜᱤᱱ (ramesh@example.com)",
        "login_title": "SchemeMate AI ᱞᱚᱜᱤᱱ",
        "create_account_title": "ᱱᱟᱶᱟ ᱮᱠᱟᱣᱩᱱᱴ ᱵᱮᱱᱟᱣ ᱢᱮ",
        "tab_login": "ᱞᱚᱜᱤᱱ",
        "tab_create_account": "ᱮᱠᱟᱣᱩᱱᱴ ᱵᱮᱱᱟᱣ ᱢᱮ",
        "registered_email": "ᱤᱢᱮᱞ ᱴᱷᱤᱠᱟᱹᱱᱟ",
        "email_hint": "ᱡᱮᱞᱮᱠᱟ: name@example.com",
        "password": "ᱯᱟᱥᱣᱟᱨᱰ",
        "password_hint": "ᱯᱟᱥᱣᱟᱨᱰ ᱮᱢ ᱢᱮ",
        "password_min_hint": "ᱠᱚᱢ ᱠᱷᱚᱱ ᱠᱚᱢ ᱖ ᱴᱟᱝ ᱚᱞ",
        "full_name": "ᱯᱩᱨᱟᱹ ᱧᱩᱛᱩᱢ",
        "full_name_hint": "ᱡᱮᱞᱮᱠᱟ: ᱨᱟᱢᱮᱥ ᱠᱩᱢᱟᱨ",
        "phone_number": "ᱯᱷᱚᱱ ᱱᱚᱢᱵᱚᱨ",
        "phone_hint": "᱑᱐ ᱴᱟᱝ ᱱᱚᱢᱵᱚᱨ",
        "btn_login_submit": "ᱞᱚᱜᱤᱱ ᱢᱮ",
        "btn_register_submit": "ᱮᱠᱟᱣᱩᱱᱴ ᱵᱮᱱᱟᱣ ᱢᱮ ᱟᱨ OTP ᱧᱟᱢ ᱢᱮ",
        "otp_title": "OTP ᱡᱟᱸᱪ ᱢᱮ",
        "otp_subtitle": "ᱤᱢᱮᱞ ᱨᱮ ᱵᱷᱮᱡᱟ ᱟᱠᱟᱱ ᱖ ᱴᱟᱝ ᱠᱚᱰ ᱮᱢ ᱢᱮ:",
        "resend_otp": "ᱟᱨᱦᱚᱸ ᱵᱷᱮᱡᱟᱭ ᱢᱮ",
        "resend_in": "{seconds} ᱥᱮᱠᱮᱱᱰ ᱨᱮ",
        "verify_otp_btn": "OTP ᱡᱟᱸᱪ ᱢᱮ ᱟᱨ ᱮᱠᱟᱣᱩᱱᱴ ᱪᱟᱹᱞᱩ ᱢᱮ",
        "cancel": "ᱵᱟᱹᱜᱤᱭᱟᱜ ᱢᱮ",
        "hello_user": "ᱡᱚᱦᱟᱨ, {name} 👋",
        "edit_form": "ᱯᱷᱚᱨᱢ ᱵᱚᱫᱚᱞ ᱢᱮ",
        "details_prefix": "📝 ᱵᱤᱵᱚᱨᱚᱱ: ",
        "age_chip": "ᱩᱢᱮᱨ: {age} ᱥᱮᱨᱢᱟ",
        "category_chip": "ᱛᱷᱚᱠ: {category}",
        "income_chip": "ᱟᱨᱡᱟᱣ: ₹{income}/ᱥᱮᱨᱢᱟ ({source})",
        "verified_chip": "ᱡᱟᱸᱪ ᱟᱠᱟᱱ: {type} (#{number})",
        "verified_chip_no_num": "ᱡᱟᱸᱪ ᱟᱠᱟᱱ: {type}",
        "profile_completion": "ᱯᱨᱚᱯᱷᱟᱭᱤᱞ ᱯᱩᱨᱟᱹᱣ: ",
        "suggested_schemes": "ᱟᱢ ᱞᱟᱹᱜᱤᱫ ᱥᱠᱤᱢ ᱠᱚ",
        "refresh_suggestions": "ᱱᱟᱶᱟ ᱛᱮ ᱧᱟᱢ ᱢᱮ",
        "no_suggestions": "ᱪᱮᱫ ᱥᱠᱤᱢ ᱦᱚᱸ ᱵᱟᱹᱱᱩᱜᱼᱟ। ᱯᱨᱚᱯᱷᱟᱭᱤᱞ ᱯᱩᱨᱟᱹᱣ ᱢᱮ।",
        "view_required_details_btn": "ᱵᱤᱵᱚᱨᱚᱱ ᱧᱮᱞ ᱢᱮ ᱟᱨ ᱮᱯᱞᱟᱭ ᱢᱮ",
        "offline_mode_active": "ᱚᱯᱷᱞᱟᱭᱤᱱ ᱢᱚᱰ ᱪᱟᱹᱞᱩ ᱢᱮᱱᱟᱜᱼᱟ",
        "change_language": "ᱯᱟᱹᱨᱥᱤ ᱵᱚᱫᱚᱞ ᱢᱮ",
        "required_details_title": "ᱞᱟᱹᱠᱛᱤᱭᱟᱱ ᱵᱤᱵᱚᱨᱚᱱ",
        "why_matches_heading": "ᱱᱚᱣᱟ ᱥᱠᱤᱢ ᱟᱢ ᱞᱟᱹᱜᱤᱫ ᱪᱮᱫᱟᱜ ᱵᱩᱜᱤᱭᱟ",
        "required_certificates_heading": "ᱞᱟᱹᱠᱛᱤᱭᱟᱱ ᱥᱟᱠᱟᱢ ᱠᱚ",
        "prepare_before_applying": "ᱮᱯᱞᱟᱭ ᱢᱟᱲᱟᱝ ᱱᱚᱣᱟ ᱠᱚ ᱥᱟᱯᱲᱟᱣ ᱢᱮ:",
        "badge_required": "ᱞᱟᱹᱠᱛᱤᱜᱼᱟ",
        "badge_optional": "ᱤᱪᱷᱟᱹ",
        "standard_kyc_note": "KYC ᱥᱟᱠᱟᱢ ᱠᱚ:\n• ᱟᱫᱷᱟᱨ ᱠᱟᱨᱰ\n• ᱯᱮᱱ ᱠᱟᱨᱰ\n• ᱵᱮᱸᱠ ᱯᱟᱥᱵᱩᱠ\n• ᱯᱷᱚᱴᱚ",
        "apply_online_btn": "ᱚᱱᱞᱟᱭᱤᱱ ᱮᱯᱞᱟᱭ ᱢᱮ",
        "redirect_notice": "ᱥᱚᱨᱠᱟᱨᱤ ᱣᱮᱵᱽᱥᱟᱭᱤᱴ ᱛᱮᱢ ᱪᱟᱞᱟᱜᱼᱟ",
        "no_portal_url": "ᱪᱮᱫ ᱞᱤᱝᱠ ᱦᱚᱸ ᱵᱟᱹᱱᱩᱜᱼᱟ।",
        "action_plan_title": "ᱠᱟᱹᱢᱤ ᱦᱚᱨᱟ ᱯᱞᱟᱱ",
        "action_plan_for": "{scheme} ᱞᱟᱹᱜᱤᱫ ᱯᱞᱟᱱ",
        "administered_by": "ᱥᱟᱥᱚᱱ: {ministry}",
        "step_1_title": "ᱡᱚᱜᱽᱭᱚᱛᱟ ᱡᱟᱸᱪ ᱢᱮ",
        "step_1_desc": "ᱩᱢᱮᱨ ᱟᱨ ᱟᱨᱡᱟᱣ ᱢᱤᱞᱟᱹᱣ ᱢᱮ।",
        "step_2_title": "ᱥᱟᱠᱟᱢ ᱠᱚ ᱡᱟᱣᱨᱟᱭ ᱢᱮ",
        "step_2_desc": "ᱟᱫᱷᱟᱨ ᱟᱨ ᱯᱮᱱ ᱠᱟᱨᱰ ᱡᱟᱣᱨᱟᱭ ᱢᱮ।",
        "step_3_title": "ᱯᱩᱨᱟᱹᱣ ᱢᱮ",
        "step_3_desc": "OCR ᱛᱮ ᱡᱟᱸᱪ ᱢᱮ।",
        "step_4_title": "ᱣᱮᱵᱽᱥᱟᱭᱤᱴ ᱡᱷᱤᱡᱽ ᱢᱮ",
        "step_4_desc": "ᱥᱚᱨᱠᱟᱨᱤ ᱯᱚᱨᱴᱟᱞ ᱛᱮ ᱪᱟᱞᱟᱜ ᱢᱮ।",
        "step_5_title": "ᱮᱢ ᱢᱮ ᱟᱨ ᱧᱮᱞ ᱢᱮ",
        "step_5_desc": "ᱱᱚᱢᱵᱚᱨ ᱫᱚᱦᱚ ᱢᱮ।",
        "open_verified_portal_btn": "ᱥᱚᱨᱠᱟᱨᱤ ᱯᱚᱨᱴᱟᱞ ᱡᱷᱤᱡᱽ ᱢᱮ",
        "profile_form_title": "ᱵᱮᱯᱟᱨ ᱯᱨᱚᱯᱷᱟᱭᱤᱞ",
        "profile_banner_info": "ᱵᱮᱯᱟᱨ ᱨᱮᱱᱟᱜ ᱵᱤᱵᱚᱨᱚᱱ ᱮᱢ ᱢᱮ। AI ᱥᱠᱤᱢ ᱧᱟᱢᱟ।",
        "field_company_name": "᱑. ᱠᱚᱢᱯᱟᱱᱤ ᱧᱩᱛᱩᱢ",
        "hint_company_name": "ᱡᱮᱞᱮᱠᱟ: ᱥᱨᱤ ᱞᱚᱠᱥᱢᱤ",
        "field_business_desc": "᱒. ᱵᱮᱯᱟᱨ ᱨᱮᱱᱟᱜ ᱵᱤᱵᱚᱨᱚᱱ",
        "hint_business_desc": "ᱡᱮᱞᱮᱠᱟ: ᱞᱩᱜᱽᱲᱤ ᱵᱮᱱᱟᱣ ᱟᱨ ᱟᱹᱠᱷᱨᱤᱧ",
        "field_business_type": "᱓. ᱵᱮᱯᱟᱨ ᱨᱮᱱᱟᱜ ᱛᱷᱚᱠ",
        "field_state": "᱔. ᱯᱚᱱᱚᱛ",
        "field_age": "᱕. ᱩᱢᱮᱨ",
        "hint_age": "ᱩᱢᱮᱨ",
        "field_annual_income": "᱖. ᱥᱮᱨᱢᱟᱠᱤᱭᱟᱹ ᱟᱨᱡᱟᱣ (₹)",
        "hint_annual_income": "ᱟᱨᱡᱟᱣ",
        "field_income_source": "᱗. ᱟᱨᱡᱟᱣ ᱨᱮᱱᱟᱜ ᱰᱟᱦᱟᱨ",
        "field_category_caste": "᱘. ᱡᱟᱹᱛᱤ / ᱛᱷᱚᱠ",
        "field_certificate_section": "᱙. ᱥᱟᱠᱟᱢ ᱱᱚᱢᱵᱚᱨ (ᱞᱟᱹᱠᱛᱤᱜᱼᱟ)",
        "certificate_section_desc": "ᱥᱟᱠᱟᱢ ᱱᱚᱢᱵᱚᱨ ᱮᱢ ᱢᱮ।",
        "select_cert_type": "ᱥᱟᱠᱟᱢ ᱛᱷᱚᱠ ᱵᱟᱪᱷᱟᱣ ᱢᱮ",
        "cert_linked": "ᱡᱚᱲᱟᱣ ᱟᱠᱟᱱ: ",
        "btn_save_profile": "ᱯᱨᱚᱯᱷᱟᱭᱤᱞ ᱫᱚᱦᱚᱭ ᱢᱮ ->",
        "field_custom_business_type": "ᱵᱮᱯᱟᱨ ᱛᱷᱚᱠ ᱚᱞ ᱢᱮ",
        "hint_custom_business_type": "ᱡᱮᱞᱮᱠᱟ: ᱰᱨᱚᱱ ᱠᱟᱹᱢᱤ",
        "field_custom_state": "ᱯᱚᱱᱚᱛ ᱚᱞ ᱢᱮ",
        "hint_custom_state": "ᱡᱮᱞᱮᱠᱟ: ᱡᱷᱟᱨᱠᱷᱚᱸᱰ,  Odisha",
        "field_custom_caste": "ᱡᱟᱹᱛᱤ ᱧᱩᱛᱩᱢ ᱚᱞ ᱢᱮ",
        "hint_custom_caste": "ᱡᱮᱞᱮᱠᱟ: ᱥᱟᱱᱛᱟᱲ, ᱢᱩᱱᱰᱟ ᱟᱹᱫᱤ",
        "view_all_languages": "ᱡᱚᱛᱚ ᱒᱓ ᱴᱟᱝ ᱯᱟᱹᱨᱥᱤ ᱧᱮᱞ ᱢᱮ ->",
        "last_date": "ᱢᱩᱪᱟᱹᱫ ᱢᱟᱹᱦᱤᱛ",
        "calc_title": "ᱥᱠᱤᱢ ᱨᱤᱬ ᱟᱨ EMI ᱞᱮᱠᱷᱟ",
        "calc_presets_heading": "ᱥᱠᱤᱢ ᱠᱚ:",
        "calc_loan_amount_label": "ᱞᱟᱹᱠᱛᱤᱭᱟᱱ ᱨᱤᱬ:",
        "calc_interest_rate_label": "ᱥᱩᱫᱽ (%):",
        "calc_moratorium_label": "ᱪᱷᱟᱹᱲ ᱚᱠᱛᱚ (ᱪᱟᱸᱫᱚ):",
        "calc_tenure_label": "ᱨᱩᱣᱟᱹᱲ ᱚᱠᱛᱚ:",
        "calc_subsidy_pct_label": "ᱥᱚᱨᱠᱟᱨᱤ ᱜᱚᱲᱚ (%):",
        "calc_monthly_emi": "ᱪᱟᱸᱫᱚᱠᱤᱭᱟᱹ EMI",
        "calc_moratorium_monthly": "ᱪᱷᱟᱹᱲ ᱚᱠᱛᱚ ᱨᱮᱱᱟᱜ EMI",
        "calc_subsidy_credit": "ᱜᱚᱲᱚ ᱴᱟᱠᱟ",
        "calc_gross_loan": "ᱜᱩᱴ ᱨᱤᱬ:",
        "calc_net_loan": "ᱥᱟᱨᱮᱡ ᱨᱤᱬ:",
        "calc_total_interest": "ᱜᱩᱴ ᱥᱩᱫᱽ:",
        "calc_total_outflow": "ᱮᱢᱚᱜ ᱜᱩᱴ ᱴᱟᱠᱟ:",
        "months_suffix": "ᱪᱟᱸᱫᱚ",
        "months_grace": "ᱪᱟᱸᱫᱚ ᱪᱷᱟᱹᱲ",
        "partner_locator_title": "ᱥᱩᱨ ᱨᱮᱱᱟᱜ ᱵᱮᱸᱠ",
        "live_gps": "ᱞᱟᱭᱤᱵᱽ GPS",
        "gps_update": "GPS ᱱᱟᱶᱟᱭ ᱢᱮ",
        "partners_found": "ᱵᱮᱸᱠ ᱧᱟᱢᱮᱱᱟ",
        "eligible_healthy": "ᱵᱩᱜᱤ",
        "get_directions": "ᱦᱚᱨ ᱧᱮᱞ ᱢᱮ",
        "routing_disabled": "ᱦᱚᱨ ᱵᱚᱱᱫᱚ",
        "calculate_emi": "EMI ᱞᱮᱠᱷᱟᱭ ᱢᱮ",
        "locate_partner": "ᱵᱮᱸᱠ ᱧᱟᱢ ᱢᱮ"
    },
    "sd": {
        "select_your_language": "پنهنجي پسند جي ٻولي چونڊيو",
        "select_language_subtitle": "سڄي ائپ ۾ استعمال لاءِ پنهنجي ٻولي چونڊيو:",
        "welcome_header": "SchemeMate AI ۾ ڀلي ڪري آيا",
        "welcome_subheading": "پنهنجي ڪاروبار لاءِ سرڪاري اسڪيمون ۽ قرض پنهنجي ٻوليءَ ۾ ڳوليو.",
        "feature_ai_matching": "ذاتي اسڪيم جي چونڊ",
        "feature_ai_matching_desc": "ڪاروبار ۽ عمر جي حساب سان صحيح اسڪيمون.",
        "feature_docs": "ضروري دستاويزن جي لسٽ",
        "feature_docs_desc": "درخواست ڏيڻ کان اڳ ضروري سرٽيفڪيٽ.",
        "feature_portal": "سرڪاري پورٽل جو لنڪ",
        "feature_portal_desc": "سرڪاري ويب سائيٽ تي محفوظ رسائي.",
        "btn_create_account": "نئون اڪائونٽ ٺاهيو / رجسٽر ڪريو",
        "btn_login": "لاگ ان ڪريو",
        "btn_continue": "جاري رکو",
        "btn_demo_login": "ڊيمو لاگ ان (ramesh@example.com)",
        "login_title": "SchemeMate AI لاگ ان",
        "create_account_title": "نئون اڪائونٽ ٺاهيو",
        "tab_login": "لاگ ان",
        "tab_create_account": "اڪائونٽ ٺاهيو",
        "registered_email": "رجسٽرڊ اي ميل پتو",
        "email_hint": "مثال: name@example.com",
        "password": "پاسورڊ",
        "password_hint": "پنهنجو پاسورڊ داخل ڪريو",
        "password_min_hint": "گھٽ ۾ گھٽ 6 اکر",
        "full_name": "پورو نالو",
        "full_name_hint": "مثال: رميش ڪمار",
        "phone_number": "فون نمبر",
        "phone_hint": "10 نمبرن جو موبائل نمبر",
        "btn_login_submit": "لاگ ان ڪريو",
        "btn_register_submit": "اڪائونٽ ٺاهيو ۽ OTP حاصل ڪريو",
        "otp_title": "اي ميل OTP تصديق ڪريو",
        "otp_subtitle": "اي ميل تي موڪليل 6 نمبرن جو ڪوڊ داخل ڪريو:",
        "resend_otp": "ٻيهر موڪليو",
        "resend_in": "{seconds} سيڪنڊن ۾",
        "verify_otp_btn": "تصديق ڪريو",
        "cancel": "منسوخ",
        "hello_user": "ڀلي ڪري آيا، {name} 👋",
        "edit_form": "فارم ۾ تبديلي",
        "details_prefix": "📝 تفصيل: ",
        "age_chip": "عمر: {age} سال",
        "category_chip": "زمرو: {category}",
        "income_chip": "آمدني: ₹{income}/سال ({source})",
        "verified_chip": "مصدقہ: {type} (#{number})",
        "verified_chip_no_num": "مصدقہ: {type}",
        "profile_completion": "پروفائل: ",
        "suggested_schemes": "توهان لاءِ اسڪيمون",
        "refresh_suggestions": "تازو ڪريو",
        "no_suggestions": "ڪابه اسڪيم ناهي.",
        "view_required_details_btn": "تفصيل ڏسو ۽ درخواست ڏيو",
        "offline_mode_active": "آف لائن موڊ",
        "change_language": "ٻولي مٽايو",
        "required_details_title": "ضروري تفصيل",
        "why_matches_heading": "هيءَ اسڪيم ڇو صحيح آهي",
        "required_certificates_heading": "ضروري دستاويز",
        "prepare_before_applying": "درخواست ڏيڻ کان اڳ تيار رکو:",
        "badge_required": "لازمي",
        "badge_optional": "اخياري",
        "standard_kyc_note": "بنيادي KYC دستاويز:\n• آڌار ڪارڊ\n• پين ڪارڊ\n• پاس بڪ\n• فوٽو",
        "apply_online_btn": "آن لائن درخواست ڏيو",
        "redirect_notice": "توهان کي سرڪاري ويب سائيٽ تي منتقل ڪيو ويندو",
        "no_portal_url": "ڪوبه لنڪ ناهي.",
        "action_plan_title": "طريقيڪار",
        "action_plan_for": "{scheme} لاءِ پلان",
        "administered_by": "وزارت: {ministry}",
        "step_1_title": "اهليت چيڪ ڪريو",
        "step_1_desc": "عمر ۽ آمدني ملائيو.",
        "step_2_title": "دستاويز گڏ ڪريو",
        "step_2_desc": "آڌار ۽ پين ڪارڊ گڏ ڪريو.",
        "step_3_title": "باقي پورو ڪريو",
        "step_3_desc": "اسڪين ڪريو.",
        "step_4_title": "پورٽل کوليو",
        "step_4_desc": "سرڪاري ویب سائيٽ تي وڃو.",
        "step_5_title": "جمع ڪريو",
        "step_5_desc": "نمبر محفوظ رکو.",
        "open_verified_portal_btn": "سرڪاري پورٽل کوليو",
        "profile_form_title": "ڪاروباري پروفائل",
        "profile_banner_info": "تفصيل داخل ڪريو. AI اسڪيمون ڳوليندو.",
        "field_company_name": "1. ڪمپنيءَ جو نالو",
        "hint_company_name": "مثال: شري لڪشمي",
        "field_business_desc": "2. ڪاروبار جو تفصيل",
        "hint_business_desc": "مثال: ڪپڙن جو ڪم",
        "field_business_type": "3. قسم",
        "field_state": "4. رياست",
        "field_age": "5. عمر",
        "hint_age": "عمر",
        "field_annual_income": "6. سالياني آمدني (₹)",
        "hint_annual_income": "آمدني",
        "field_income_source": "7. ذريعو",
        "field_category_caste": "8. زمرو",
        "field_certificate_section": "9. سرٽيفڪيٽ نمبر",
        "certificate_section_desc": "نمبر داخل ڪريو.",
        "select_cert_type": "قسم چونڊيو",
        "cert_linked": "منسلڪ: ",
        "btn_save_profile": "محفوظ ڪريو ->",
        "field_custom_business_type": "قسم داخل ڪريو",
        "hint_custom_business_type": "مثال: ڊرون ڪم",
        "field_custom_state": "رياست داخل ڪريو",
        "hint_custom_state": "مثال: گجرات, راجستان",
        "field_custom_caste": "ذات داخل ڪريو",
        "hint_custom_caste": "مثال: سنڌي, لوهاڻو وغيره",
        "view_all_languages": "تمام 23 ٻوليون ڏسو ->",
        "last_date": "آخري تاريخ",
        "calc_title": "لون ۽ EMI ڪئلڪيوليٽر",
        "calc_presets_heading": "اسڪيمون:",
        "calc_loan_amount_label": "قرض:",
        "calc_interest_rate_label": "سود (%):",
        "calc_moratorium_label": "مهلت (مهينا):",
        "calc_tenure_label": "وقت:",
        "calc_subsidy_pct_label": "سبسيڊي (%):",
        "calc_monthly_emi": "ماھوار EMI",
        "calc_moratorium_monthly": "مهلت جي EMI",
        "calc_subsidy_credit": "سبسيڊي رقم",
        "calc_gross_loan": "ڪل قرض:",
        "calc_net_loan": "باقي قرض:",
        "calc_total_interest": "ڪل سود:",
        "calc_total_outflow": "ڪل رقم:",
        "months_suffix": "مهينا",
        "months_grace": "مهينا مهلت",
        "partner_locator_title": "قريبي بئنڪون",
        "live_gps": "لائيو GPS",
        "gps_update": "تازو ڪريو",
        "partners_found": "بئنڪون مليون",
        "eligible_healthy": "اهل",
        "get_directions": "راستو ڏسو",
        "routing_disabled": "راستو بند",
        "calculate_emi": "EMI ڳڻيو",
        "locate_partner": "بئنڪ ڳوليو"
    }
}

# Update JSON files for every remaining language code
for lang_code, trans in remaining_translations.items():
    file_path = os.path.join(i18n_dir, f"{lang_code}.json")
    data = {}
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)

    # Merge master en keys with target translation dict
    for k, default_val in en_dict.items():
        if k in trans:
            data[k] = trans[k]
        elif k not in data or data[k] == default_val:
            pass

    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

print("Remaining 10 language JSON assets updated successfully!")

