# -*- coding: utf-8 -*-
import json
import os

i18n_dir = r"C:\dev\scheme-mate-ai\mobile\flutter_app\assets\i18n"
en_path = os.path.join(i18n_dir, "en.json")
with open(en_path, "r", encoding="utf-8") as f:
    en_dict = json.load(f)

brx_trans = {
    "select_your_language": "गावनि मोजां मोन्नाय रावखौ सायख'",
    "select_language_subtitle": "गासै एपआव बाहायनो थाखाय रावखौ सायख':",
    "welcome_header": "स्कीममेट AI आव साबायखर",
    "welcome_subheading": "नांगौगुनां सुबिधा आरो ऋनखौ गावनि रावआव नाय।",
    "feature_ai_matching": "गावजों नांथाबानाय आसनि",
    "feature_ai_matching_desc": "फालांगि, बैसो आरो हारिनि सायाव सोंनानै आसनि सायख'।",
    "feature_docs": "नांगौगुनां लाइसि",
    "feature_docs_desc": "आरज गाबनायनि सिगां नांगौगुनां लाइसिनि फारिलाइ।",
    "feature_portal": "सोरखारनि वेबसाइत लिंक",
    "feature_portal_desc": "सोरखारनि आरज गाबग्रा वेबसाइतआव सोबनाय।",
    "btn_create_account": "गोदान एकाउन्ट बानाय / रेजिस्टार",
    "btn_login": "लगइन खालाम",
    "btn_continue": "आगायाव थां",
    "btn_demo_login": "दिन्थिसिन लगइन (ramesh@example.com)",
    "login_title": "स्कीममेट AI लगइन",
    "create_account_title": "गोदान एकाउन्ट बानाय",
    "tab_login": "लगइन",
    "tab_create_account": "एकाउन्ट बानाय",
    "registered_email": "इमेल थिकना",
    "email_hint": "जेरै: name@example.com",
    "password": "पासवर्ड",
    "password_hint": "पासवर्ड हो",
    "password_min_hint": "खोमसिबो ६ हांखो",
    "full_name": "मुंखौ लिर",
    "full_name_hint": "जेरै: रमेश कुमार",
    "phone_number": "फन नम्बर",
    "phone_hint": "१०-अनं मोबाइल नम्बर",
    "btn_login_submit": "लगइन खालाम",
    "btn_register_submit": "एकाउन्ट बानाय आरो OTP लाय",
    "otp_title": "इमेल OTP आनजाद खालाम",
    "otp_subtitle": "इमेलआव दैथायहरनाय ६-अनं कडखौ लिर:",
    "resend_otp": "फिन OTP दैथायहर",
    "resend_in": "{seconds} सेकेन्दआव फिन हर",
    "verify_otp_btn": "OTP आनजाद खालाम आरो एकाउन्ट जागाय",
    "cancel": "बन्द खालाम",
    "hello_user": "खुमुलाय, {name} 👋",
    "edit_form": "फ्राम सोलाय",
    "details_prefix": "📝 गुवारै: ",
    "age_chip": "बैसो: {age} बछर",
    "category_chip": "थिगुरि: {category}",
    "income_chip": "आय: ₹{income}/बछर ({source})",
    "verified_chip": "आनजाद खालामनाय: {type} (#{number})",
    "verified_chip_no_num": "आनजाद खालामनाय: {type}",
    "profile_completion": "प्रफाइल आबुं: ",
    "suggested_schemes": "नोंनि थाखाय आसनिफोर",
    "refresh_suggestions": "गोदान खालाम",
    "no_suggestions": "गैया। गावनि प्रफाइलखौ आबुं खालाम।",
    "view_required_details_btn": "नांगौगुनां गुवारै नाय आरो आरज गाब",
    "offline_mode_active": "अफलाइन मड आव दङ",
    "change_language": "राव सोलाय",
    "required_details_title": "नांगौगुनां गुवारै",
    "why_matches_heading": "मानो बे आसनिया नोंनि थाखाय मोजां",
    "required_certificates_heading": "नांगौगुनां लाइसिफोर",
    "prepare_before_applying": "आरज गाबनायनि सिगां बेफोरखौ थयार खालाम:",
    "badge_required": "नांगौगोन",
    "badge_optional": "बायदि",
    "standard_kyc_note": "नांगौगुनां KYC लाइसि:\n• आधार कार्ड\n• पान कार्ड\n• बैंक पासबुक\n• फोटो",
    "apply_online_btn": "अनलाइन आरज गाब",
    "redirect_notice": "सोरखारनि वेबसाइतआव थांगोन",
    "no_portal_url": "वेबसाइत लिंक गैया।",
    "action_plan_title": "मावथांखि फारिलाइ",
    "action_plan_for": "{scheme} नि थाखाय थांखि",
    "administered_by": "सामलायनाय: {ministry}",
    "step_1_title": "थाखाय आनजाद खालाम",
    "step_1_desc": "बैसो आरो आयखौ नियमजों मिलाय।",
    "step_2_title": "लाइसीनिर फारिलाइ बानाय",
    "step_2_desc": "आधार आरो पान कार्ड जमा खालाम।",
    "step_3_title": "आबुं खालाम",
    "step_3_desc": "OCR जों आनजाद खालाम।",
    "step_4_title": "वेबसाइत खेव",
    "step_4_desc": "सोरखारनि पोर्टेलआव थां।",
    "step_5_title": "आरज गाब आरो नायगिनाय खालाम",
    "step_5_desc": "नमबरखौ लिरना दोन।",
    "open_verified_portal_btn": "सोरखारनि वेबसाइत खेव",
    "profile_form_title": "फालांगियारि प्रफाइल",
    "profile_banner_info": "फालांगिनि गुवारै लिर। AI आ आसनि हुइगोन।",
    "field_company_name": "১. कम्पानिनि मुं",
    "hint_company_name": "जेरै: श्री लक्ष्मी टेक्सटाइल",
    "field_business_desc": "২. फालांगिनि गुवारै",
    "hint_business_desc": "जेरै: सिइनाय आरो फाननाय",
    "field_business_type": "३. फालांगिनि रोखोम",
    "field_state": "४. रायजो",
    "field_age": "५. बैसो",
    "hint_age": "बैसो",
    "field_annual_income": "६. बछरनि आय (₹)",
    "hint_annual_income": "आय",
    "field_income_source": "৭. आयनि फुंखा",
    "field_category_caste": "৮. हारि / थिगुरि",
    "field_certificate_section": "৯. लाइसि अनं (नांगौगोन)",
    "certificate_section_desc": "नांगौगुनां अनंखौ लिर।",
    "select_cert_type": "लाइसीनिर रोखोम सायख'",
    "cert_linked": "सोमोन्दो गोनां लाइसि: ",
    "btn_save_profile": "प्रफाइल दोन आरो आसनि नाय ->",
    "field_custom_business_type": "फालांगिनि रोखोम लिर",
    "hint_custom_business_type": "जेरै: ड्रोन, मैहा",
    "field_custom_state": "रायजो लिर",
    "hint_custom_state": "जेरै: आसाम",
    "field_custom_caste": "हारिनि मुं लिर",
    "hint_custom_caste": "जेरै: बर'",
    "view_all_languages": "गासै ২৩ টা रावखौ नाय ->",
    "last_date": "जोबथा सान",
    "calc_title": "ऋन आरो EMI हसाब",
    "calc_presets_heading": "मुंदांखा आसनि:",
    "calc_loan_amount_label": "नांगौगुनां ऋन:",
    "calc_interest_rate_label": "सुद (%):",
    "calc_moratorium_label": "मोरेतोरियम (दान):",
    "calc_tenure_label": "जोबथा समाव:",
    "calc_subsidy_pct_label": "सोरखारनि मदद (%):",
    "calc_monthly_emi": "दाननि EMI",
    "calc_moratorium_monthly": "रेहाय दाननि",
    "calc_subsidy_credit": "सोरखारनि मदद रां",
    "calc_gross_loan": "गासै ऋन:",
    "calc_net_loan": "आबुं ऋन:",
    "calc_total_interest": "गासै सुद:",
    "calc_total_outflow": "गासै होनांगौ रां:",
    "months_suffix": "दान",
    "months_grace": "दान रेहाय",
    "partner_locator_title": "खाथिनायनि बैंक",
    "live_gps": "लाइभ GPS",
    "gps_update": "GPS गोदान खालाम",
    "partners_found": "बैंक मोन्नाय जाबाय",
    "eligible_healthy": "मोजां",
    "get_directions": "लामा नाय",
    "routing_disabled": "लामा बन्द",
    "calculate_emi": "EMI हसाब खालाम",
    "locate_partner": "बैंक नागिर"
}

file_path = os.path.join(i18n_dir, "brx.json")
with open(file_path, "r", encoding="utf-8") as f:
    data = json.load(f)

for k, v in brx_trans.items():
    data[k] = v

with open(file_path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Bodo (brx) updated!")

